#!/bin/bash
# ftext: find specific text inside text files using "find".
# 
# usage: ftext where what
#
# example: ftext ~/workspace/codebase/ Callback
# example: ftext ~/workspace/codebase/ "class Square"
#
# It also supports regular expression (the format is the same as in grep):
# example: ftext ~/workspace/codebase/ "class .*Square"
# example: ftext ~/workspace/codebase/ "Square|Rectangle"

# It supports Unicode and regular expression.
# example: ftext ./ "游戏..者" # This will match 游戏从业者，游戏爱好者, etc.
#
# Copyright (c) 2008 Shubao Liu (shubao.liu@gmail.com)
# All rights reserved.

if [ $# -ne 2 ]
then
  echo "Error: incorrect number of arguments"
  echo "usage: ftext path pattern"
  exit $E_BADARGS
fi

if [ -z "$1" ]
then
  echo "Error: empty path"
  echo "usage: ftext path pattern"
  exit $E_BADARGS
fi

if [ -z "$2" ]
then
  echo "Error: empty pattern"
  echo "usage: ftext path pattern"
  exit $E_BADARGS
fi

find "$1" -path '*/.svn' -prune \
    -o -path './third_party/*' -prune \
    -o -path './3rdparty/*' -prune \
    -o -path '*/build/*' -prune \
    -o -type f \
    -exec grep -n --color=auto --binary-files=without-match -E "$2" {} /dev/null \;
    #-exec grep -i -n --color=auto --binary-files=without-match "$2" {} /dev/null \;

# comment: grep is case-sensitive by default; use -i to ignore case.
