#!/bin/bash
#
# Copyright (c) 2008 Shubao Liu (shubao.liu@gmail.com)
# All rights reserved.
#
# sftext: substitute patterns in certain files
#
# example: sftext ./ *.tex side_length sidelength
# example: sftext ./ *.txt "a, b" "c, d"

if [ $# -ne 4 ]
then
  echo "Error: incorrect number of arguments"
  echo "usage: sftext path file_pattern text1 text2"
  exit $E_BADARGS
fi

if [ -z "$1" ]
then
  echo "Error: empty path"
  echo "usage: sftext path file_pattern text1 text2"
  exit $E_BADARGS
fi

if [ -z "$2" ]
then
  echo "Error: empty file pattern"
  echo "usage: sftext path file_pattern text1 text2"
  exit $E_BADARGS
fi

if [ -z "$3" ]
then
  echo "Error: empty text pattern"
  echo "usage: sftext path file_pattern text1 text2"
  exit $E_BADARGS
fi

if [ -z "$4" ]
then
  echo "Error: empty text pattern"
  echo "usage: sftext path file_pattern text1 text2"
  exit $E_BADARGS
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
  SED_CMD=gsed
else
  SED_CMD=sed
fi

find "$1" -path '*/.svn' -prune \
    -o -path './third_party/*' -prune \
    -o -path './3rdparty/*' -prune \
    -o -path '*/build/*' -prune \
    -o -path '*/doc' -prune \
    -o -type f \
    -name "$2" \
    -exec ${SED_CMD} -i 's/'"$3"'/'"$4"'/g' {} \;

# comment:
# Passing arguments into a sed script: http://www.grymoire.com/Unix/Sed.html#uh-22
